---
- name: Configure Browbeat
  hosts: undercloud
  roles:
    - browbeat/pre-install-setup

- name: Install Browbeat
  hosts: undercloud
  vars:
    results_in_httpd: false
    statsd_host: "{{ graphite_host }}"
  roles:
    - browbeat/common
    - browbeat/browbeat
    - browbeat/browbeat-network
    - browbeat/template-configs
    - browbeat/statsd-ironic

- name: Disable sshd dns
  hosts: overcloud
  vars:
    disable_ssh_dns: true
  roles:
    - browbeat/no-sshd-dns

- name: Run Browbeat
  hosts: undercloud
  roles:
    - browbeat/collectd
    - browbeat/bug-check
    - browbeat/grafana-dashboard-setup
    - browbeat/browbeat-run
